name: Cypress E2E Tests

on:
    schedule:
        - cron: '0 23 * * 0-4' # UTC 기준 매주 일요일 ~ 수요일 23:00 (11:00 PM)에 실행
    push:
        branches:
            - main

env:
    TZ: 'Asia/Seoul'

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '21.7.1'
            - run: yarn add cypress

            - name: Install dependencies
              run: yarn install

            - name: Run Cypress tests
              env:
                  CYPRESS_SCREEN_WIDTH: 1920
                  CYPRESS_SCREEN_HEIGHT: 1080
                  CYPRESS_browser: chrome
              run: yarn cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --spec "cypress/e2e/project/test/test.cy.js" --browser chrome
